### ISSUE TITLE
刚问学长这是复现的iCaRL、EWC、LwF的哪个算法呢，请问可以看看当时你们的报告吗

### ISSUE THREAD

**Issue by YangWenTao2** [ArizaQ/MachineLearning#3]

**Comment by YangWenTao2** [comment]
敢问学长这是复现的iCaRL、EWC、LwF的哪个算法呢，请问可以看看当时你们的报告吗

**Comment by ArizaQ** [comment]
是BiC算法
[BIC算法复现实验报告.pdf](https://github.com/ArizaQ/MachineLearning/files/11306365/BIC.pdf)

**Comment by YangWenTao2** [comment]
看到啦，感谢学长啦！
